version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    parallelism: 4
  
    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run: 
          name: yarn install
          command: yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache        
          
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: yarn test
          command: |
            TESTFILES=$(circleci tests glob "src/tests/*.{js,ts,tsx}")
            echo $TESTFILES | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
            TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
            echo Worker $CIRCLE_NODE_INDEX test files
            echo $TESTFILES | tr ' ' '\n'
            JEST_JUNIT_OUTPUT_FILE=reports/junit/js-test-results-$CIRCLE_NODE_INDEX.xml yarn test $TESTFILES --coverage --ci -i --reporters=default --reporters=jest-junit

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

      - run:
          name: Checking coverage reports
          command: |
            mv coverage/coverage-final.json coverage/coverage-final-$CIRCLE_NODE_INDEX.json
            ls coverage

      - persist_to_workspace:
          root: .
          paths:
            - coverage
  
  report:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: yarn install
          command: yarn install --ignore-engines

      - attach_workspace:
          at: .
      
      - run:
          name: List coverage content
          command: |
            ls coverage
      
      - run:
          name: Map coverage reports
          command: |
            yarn nyc merge coverage coverage/coverage-final.json
            rm -r coverage/coverage-final-*
            ls coverage
      
      - run:
          name: Check merged report
          command: |
            cat coverage/coverage-final.json
            yarn nyc report -t coverage

workflows:
  test_and_report:
    jobs:
      - build
      - report:
          requires: 
            - build

